# @package _global_

env:
  config:
    mimic_early_termination:
      - mimic_early_termination_key: max_joint_err
        mimic_early_termination_thresh: 0.5
        mimic_early_termination_thresh_on_flat: 0.25
        from_other: True
        less_than: False

    mimic_dynamic_sampling:
      dynamic_weight_max: null
      sampling_criteria: mimic_early_termination
      bucket_width: 2.0

# At evaluation, disable early termination
eval_overrides:
  env:
    config:
      mimic_early_termination: null
