# @package _global_

defaults:
  - h1

robot:
  # Observation parameters
  num_bodies: 22
  self_obs_max_coords: 328  # ${eval:1+22*(3+6+3+3)-3}

  key_bodies: [ "left_ankle_link", "right_ankle_link", "left_arm_end_effector",  "right_arm_end_effector" ]

  init_state:
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_arm_end_effector_joint: 0.
      right_arm_end_effector_joint: 0.

  asset:
    collapse_fixed_joints: False # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    robot_type: h1_extended_hands
