# @package _global_

defaults:
  - base

robot:
  # Observation parameters
  num_bodies: 52
  dof_obs_size: 306
  number_of_actions: 153
  self_obs_max_coords: 778  # ${eval:1+52*(3+6+3+3)-3}

  # Control parameters
  dof_body_ids: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51 ]
  dof_offsets: [ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153 ]

  key_bodies: [ "R_Ankle", "L_Ankle", "L_Wrist", "R_Wrist" ]
  contact_bodies: [ "R_Ankle", "L_Ankle", "R_Toe", "L_Toe" ]
  right_foot_name: "R_Ankle"
  left_foot_name: "L_Ankle"

  contact_pairs_multiplier: 32
  mimic_small_marker_bodies: [ "L_Wrist", "R_Wrist", "L_Index1", "L_Index2", "L_Index3", "L_Middle1", "L_Middle2", "L_Middle3", "L_Pinky1", "L_Pinky2", "L_Pinky3", "L_Ring1", "L_Ring2", "L_Ring3", "L_Thumb1", "L_Thumb2", "L_Thumb3", "R_Index1", "R_Index2", "R_Index3", "R_Middle1", "R_Middle2", "R_Middle3", "R_Pinky1", "R_Pinky2", "R_Pinky3", "R_Ring1", "R_Ring2", "R_Ring3", "R_Thumb1", "R_Thumb2", "R_Thumb3", ]

  asset:
    robot_type: smplx_humanoid
    filter_ints: [ 0, 0, 7, 16, 12, 0, 56, 2, 33, 128, 0, 192, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ]


# Editing some env parameters to provide more precise SMPLX simulation
env:
  config:
    simulator:
      sim:
        physx:
          num_position_iterations: 8
          default_buffer_size_multiplier: 20.0
