# @package _global_

defaults:
  - base

robot:
  # Observation parameters
  num_bodies: 24
  dof_obs_size: 138
  number_of_actions: 69
  self_obs_max_coords: 358  # ${eval:1+24*(3+6+3+3)-3}

  # Control parameters
  dof_body_ids: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
  dof_offsets: [ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69 ]

  key_bodies: [ "R_Ankle", "L_Ankle", "L_Hand", "R_Hand" ]
  contact_bodies: [ "R_Ankle", "L_Ankle", "R_Toe", "L_Toe" ]
  right_foot_name: "R_Ankle"
  left_foot_name: "L_Ankle"

  asset:
    robot_type: smpl_humanoid
    filter_ints: [ 0, 0, 7, 16, 12, 0, 56, 2, 33, 128, 0, 192, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ]
